fruits = []
f1 = input("Enter a fruit name: ")
f2 = input("Enter a fruit name: ")
f3 = input("Enter a fruit name: ")
f4 = input("Enter a fruit name: ")
f5 = input("Enter a fruit name: ")
f6 = input("Enter a fruit name: ")
f7 = input("Enter a fruit name: ")
fruits.append(f1)
fruits.append(f2)
fruits.append(f3)
fruits.append(f4)
fruits.append(f5)
fruits.append(f6)
fruits.append(f7)
print(fruits)