marks = []
m1 = int(input("Enter a marks: "))
m2 = int(input("Enter a marks: "))
m3 = int(input("Enter a marks: "))
m4 = int(input("Enter a marks: "))
m5 = int(input("Enter a marks: "))
m6 = int(input("Enter a marks: "))
marks.append(m1)
marks.append(m2)
marks.append(m3)
marks.append(m4)
marks.append(m5)
marks.append(m6)
marks.sort()
print(marks)